apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: jamesrea97/accounts-k8s-project:0.0.2

---
kind: Service 
apiVersion: v1 
metadata:
  name: postgres-db-service 
spec:
  type: NodePort
  selector:
    app: postgres-db 
  ports:
    - port: 8080 
      targetPort: 5000